### ISSUE TITLE
Confusing feeback on account creation

### ISSUE THREAD

**Issue by davidbgk** [CommonsDev/sso#1]
When you create an account, you end up on that page:

![capture d ecran 2015-07-06 a 15 01 08](https://cloud.githubusercontent.com/assets/3556/8522590/dca58242-23ef-11e5-85ed-1d8f7e207034.png)

Which might be confusing given that you have to activate your account first, a better wording is required. Proposition: "Your account has been created successfully, check your inbox to activate it and then log in."

**Comment by davidbgk** [comment]
Note that when you activate your account, there is no link on the login label:

![capture d ecran 2015-07-06 a 15 03 23](https://cloud.githubusercontent.com/assets/3556/8522628/396e441e-23f0-11e5-9930-d5eb6acf3d11.png)

**Comment by vinyll** [comment]
Thanks for the review @davidbgk!
The project was rewrittent for updating and simplifying.
This confirmation message was adapted at the same time.
